export { default as ApiClient } from './client'
export type { ApiConfig, ApiResponse, ApiError } from './client'
export { BaseApiService } from './base.service'
export { UserService, userService } from './user.service'
export { ProductService, productService, fakeProductsData } from './product.service'
